name: Build and Testing
on:
  pull_request: {}
  push:
    tags:
    - 'v*.*.*'
    paths-ignore:
    - '*.md'
    - '**/*.md'

jobs:
  go_build_test:
    name: Go Build and Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
    - name: Validate go deps
      run: |
        make dep
    - name: Running go linting and unit tests
      run: |
         make lint test
  docker_build:
    name: Docker Build
    needs: go_build_test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Docker Build
      run: |
        make build
  release:
    name: Docker Push and Github Release
    needs: docker_build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
    - name: Build Chart
      run: |
        make build-chart
    - name: Docker Build and Push
      if: github.event_name == 'push'
      run: |
        export RELEASE_VERSION=${GITHUB_REF/refs\/tags\//}
        export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
        export PATH=${PATH}:`go env GOPATH`/bin
        docker login -u ${{ secrets.DOCKER_USER}} -p ${{ secrets.DOCKER_PASS}}  && \
        make push
        make release
    - name: Publish Helm chart
      uses: stefanprodan/helm-gh-pages@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        charts_dir: tmp/smi-metrics
        branch: gh-pages
        
